#pragma once

#include "KENG_Utils.hpp"

namespace KENG {
    typedef enum class EffectParserKeys { /* Effect parser keywords */
        /* CONTROL */
        CONTROL_PER,
        CONTROL_FLAT,

        /* ECONOMIC */
        TAX_PER,
        TAX_FLAT,
        BUILDING_COST_PER,

        /* MILITARY */
        MANPOWER_PER,
        MANPOWER_FLAT,
        MANPOWER_REINFORMENT_PER,
        RECRUIT_COST_PER,

        /* MILITARY LEADERS */
        LEADER_LIGHT_ATTACK_FLAT,
        LEADER_LIGHT_ATTACK_PER,
        LEADER_HEAVY_ATTACK_FLAT,
        LEADER_HEAVY_ATTACK_PER,
        LEADER_CASUALTIES_DEALT_PER,
        LEADER_LIGHT_DEFENSE_PER,
        LEADER_LIGHT_DEFENSE_FLAT,
        LEADER_HEAVY_DEFENSE_PER,
        LEADER_HEAVY_DEFENSE_FLAT,
        LEADER_MORALE_REINFORCEMENT_PER,
        LEADER_SPEED_PER,
        LEADER_TACTICS_FLAT,

        /* LIGHT UNITS */
        LIGHT_UNIT_LIGHT_ATTACK_FLAT,
        LIGHT_UNIT_LIGHT_ATTACK_PER,
        LIGHT_UNIT_HEAVY_ATTACK_FLAT,
        LIGHT_UNIT_HEAVY_ATTACK_PER,
        LIGHT_UNIT_CASUALTIES_DEALT_PER,
        LIGHT_UNIT_LIGHT_DEFENSE_PER,
        LIGHT_UNIT_LIGHT_DEFENSE_FLAT,
        LIGHT_UNIT_HEAVY_DEFENSE_PER,
        LIGHT_UNIT_HEAVY_DEFENSE_FLAT,

        /* HEAVY UNITS */
        HEAVY_UNIT_LIGHT_ATTACK_FLAT,
        HEAVY_UNIT_LIGHT_ATTACK_PER,
        HEAVY_UNIT_HEAVY_ATTACK_FLAT,
        HEAVY_UNIT_HEAVY_ATTACK_PER,
        HEAVY_UNIT_CASUALTIES_DEALT_PER,
        HEAVY_UNIT_LIGHT_DEFENSE_PER,
        HEAVY_UNIT_LIGHT_DEFENSE_FLAT,
        HEAVY_UNIT_HEAVY_DEFENSE_PER,
        HEAVY_UNIT_HEAVY_DEFENSE_FLAT,

        /* AUXILLIARY UNITS */
        AUX_UNIT_LIGHT_ATTACK_FLAT,
        AUX_UNIT_LIGHT_ATTACK_PER,
        AUX_UNIT_HEAVY_ATTACK_FLAT,
        AUX_UNIT_HEAVY_ATTACK_PER,
        AUX_UNIT_CASUALTIES_DEALT_PER,
        AUX_UNIT_LIGHT_DEFENSE_PER,
        AUX_UNIT_LIGHT_DEFENSE_FLAT,
        AUX_UNIT_HEAVY_DEFENSE_PER,
        AUX_UNIT_HEAVY_DEFENSE_FLAT,

        /* CONVERSION */
        CULTURAL_CONVERSION_COST_PER,
        CULTURAL_ACCEPTANCE_COST_PER,
        RELIGIOUS_CONVERSION_COST_PER,
        
        /* STABILITY */
        STABILITY_INCREASE_COST_PER,
    } EffectParserKeys ; // Effect Parser Keyword class

    std::unordered_map<EffectParserKeys, std::string> EffectParserKeywords; // Keywords for effect parser
} // KENG